### ISSUE TITLE
Replace Setting and SettingsExpander for the Toolkit SettingsControls

### ISSUE THREAD

**Issue by niels9001** [WinUICommunity/SettingsUI#11]
Love this initiative! We have created new SettingsCard and SettingsExpander controls for the Windows Community Toolkit (PowerToys also adopted these) that have some advantages over the prior Setting and SettingExpander controls! 

https://github.com/CommunityToolkit/Labs-Windows/tree/main/labs/SettingsControls/src

NuGet package for these controls (for UWP, WinUI and Uno) is available on this preview feed: https://github.com/CommunityToolkit/Labs-Windows#getting-started

**Comment by ghost1372** [comment]
Hi, yes, I know it and thank you very much for your work.  I have included both in this simpler package.
I ported the original version from PowerToys UWP version and new settingscontrols from labs.

I think I have already written this in the codes, I will check again and add it if not.
Tnx again.

**Comment by niels9001** [comment]
Sorry for only replying on this now :).

Particular reason why you copied over the code vs. taking a dependency on the SettingsControls Toolkit package :)? We are adding more and more features / bugfixes to these controls on a regular cadence, so if you want to have the latest and greatest pulling in the controls via the NuGet package might be easier.

Keep on rockin' 🚀

**Comment by ghost1372** [comment]
Sometimes I make changes to suit my needs. 
(Now I checked again and found that each feature is released as a separate nuget😅)
I was convinced to use it

**Comment by niels9001** [comment]
> 

Yep, you can use the CommunityToolkit.Labs.*.SettingsControls to only include the SettingsCard and SettingsExpander :). They will be included in the main Toolkit when we're releasing 8.0!
