### ISSUE TITLE
Navigate to page contains SettingsCard cause crash in dark theme

### ISSUE THREAD

**Issue by IShiraiKurokoI** [WinUICommunity/SettingsUI#12]
First,thanks for your work providing these beatiful UI,When I changed the app theme to dark through ThemeHelper and Navigate to page contains SettingsCard ,the app will crash and jump to global::System.Diagnostics.Debugger.Break(),when I hit continue it will show a exception of System.Runtime.InteropServices.COMException:“No installed components were detected. (0x800F1000)”. But all those function will work normaly in light theme.

Screenshots
![image](https://user-images.githubusercontent.com/73374735/211140065-b9386b2a-cbb1-4f72-a076-844a6bef9193.png)
![image](https://user-images.githubusercontent.com/73374735/211140073-bc658f4b-c4e5-48dc-b0a7-46e3725360fe.png)

DemoProject
https://github.com/IShiraiKurokoI/CrashDemo

**Comment by ghost1372** [comment]
Thank you for report, i will check it today.

**Comment by ghost1372** [comment]
@IShiraiKurokoI issue fixed and you can update to  WinUICommunity.SettingsUI version 3.0.1

**Comment by IShiraiKurokoI** [comment]
Thank you very much！

**Comment by IShiraiKurokoI** [comment]
> @IShiraiKurokoI issue fixed and you can update to WinUICommunity.SettingsUI version 3.0.1

Thank you very much！
