### ISSUE TITLE
Dynamically changing theme

### ISSUE THREAD

**Issue by tinmac** [WinUICommunity/SettingsUI#13]
@ghost1372 thanks for the work you've done, very handy. 

I have a question, as WinUI 3 [cant change](https://github.com/microsoft/microsoft-ui-xaml/issues/4474) the theme after app constructor, how are you acheiving this?

**Comment by ghost1372** [comment]
Hi @tinmac 
Users asked us to separate the libraries for easier access.
So the code you are looking for is [here](https://github.com/WinUICommunity/Common/blob/main/Common/Tools/Helpers/ThemeHelper.cs)
I've taken this code from Microsoft's own gallery app. I have modified it a bit to match the mica material.

Therefore, if you are looking for pure and original code, it is better to look [here](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/Helper/ThemeHelper.cs).

and we call ThemeHelper in  OnLaunched method in App.xaml.cs

**Comment by tinmac** [comment]
@ghost1372 thanks for the speedy reply, appreciate it. I will get looking through those links, thanks for the pointers.
