### ISSUE TITLE
I could not use SettingsCard or other controls from this package

### ISSUE THREAD

**Issue by WindowsAppCreate** [WinUICommunity/SettingsUI#14]
I am getting an XamlParseException. XAML parsing failed.
WinRT information: Cannot find a Resource with the Name/Key SettingsCardBackground [Line: 50 Position: 49]

**Comment by ghost1372** [comment]
Did you add ResourceDictionary in App.xaml?

**Comment by ghost1372** [comment]
> Why "xmlns:controls="using:WinUICommunity.SettingsUI.Controls" doesn't work?

We changed all namespaces to
 ```
xmlns:controls="using:WinUICommunity"
```
So change it and will be work

**Comment by ghost1372** [comment]
@WindowsAppCreate This issue occurs when you use the dark theme.
I noticed this issue now and solved it, use the new version

**Comment by WindowsAppCreate** [comment]
Done. Fix the problem because Xaml parsing failed. Add source to NuGet,
install SettingsControls and use them for a settings page.
