### ISSUE TITLE
Why "xmlns:controls="using:WinUICommunity.SettingsUI.Controls" doesn't work?

### ISSUE THREAD

**Issue by heliu-233** [WinUICommunity/SettingsUI#15]

**Comment by heliu-233** [comment]
The new assembly reference is what is not written in the documentation
I am a Chinese using Microsoft Translate content that may not be accurate

**Comment by ghost1372** [comment]
Hi @heliu-233
just change namespace to:
`xmlns:wuc="using:WinUICommunity"`

i will update all docs soon
