### ISSUE TITLE
Missing resources on the latest version

### ISSUE THREAD

**Issue by rocksdanister** [WinUICommunity/SettingsUI#16]
I am getting XamlParseException when trying to upgrade my project from SettingsUI  2.x to WinUICommunity 4.0.2

Looking at the old files, some styles are missing such as `ExpanderHeaderSettingStyle` , `ExpanderSettingMargin` .. can you take a look?

old file:
https://github.com/WinUICommunity/SettingsUI/blob/16f953d15a59797d7976a3e44515a6f21e8545a1/SettingsUI/Themes/Generic.xaml#L236

https://github.com/WinUICommunity/SettingsUI/blob/16f953d15a59797d7976a3e44515a6f21e8545a1/SettingsUI/Themes/Generic.xaml#L234

missing in the new file:
https://github.com/WinUICommunity/SettingsUI/blob/main/SettingsUI/Themes/Generic.xaml

These resources are still used in the examples:
https://ghost1372.github.io/winUICommunitySettingsUI/controls/windows11SettingsExamples/

**Comment by rocksdanister** [comment]
The big changes between versions is making it difficult to upgrade.. I hope you take that into consideration for the future😅

**Comment by rocksdanister** [comment]
From the docs:
  ```xml
  <wuc:SettingsCard
      Header="Mode"
      HeaderIcon="&#xEC4E;"
      Style="{StaticResource ExpanderHeaderSettingStyle}"/>
      ```
I am getting `ExpanderHeaderSettingStyle` missing, XamlParseException.

**Comment by ghost1372** [comment]
Oh i will check it out.
you probably don't need that style.

**Comment by ghost1372** [comment]
tnx for report, i fixed docs, and i found a bug in SettingsPageControl.
i fixed all issues and i am fixing issues in demo, i will push everythings soon

**Comment by ghost1372** [comment]
tnx again for your report
docs is now updated!
SettingsUI nuget package is now uploaded with bug fix!
Demo App is now Updated!

**Comment by rocksdanister** [comment]
Thanks for the fast response.
