### ISSUE TITLE
Program will cause a crash when I run an WinUI app without VS debugger to expand `SettingsExpander` control

### ISSUE THREAD

**Issue by SunnieShine** [WinUICommunity/SettingsUI#17]
Hi. Thanks for your `SettingsUI` control collection!

I've just encountered a bug that I don't know whether the backing bug belongs to this repo. When I use `SettingsExpander` control, I cannot expand it when the application is running without Visual Studio environment.

When I expand it, the program will cause a crash.

![test1](https://github.com/WinUICommunity/SettingsUI/assets/23616315/2b249af1-682d-4670-9ba8-0cf2ebea15ea)

This bug cannot be re-produced in VS environment. When I run it using Visual Studio:

![test2](https://github.com/WinUICommunity/SettingsUI/assets/23616315/0a043474-b7df-4959-8bee-6aa120ba3560)

It can be expanded successfully. I don't know why this behavior is so weird.

**Comment by ghost1372** [comment]
Hi @SunnieShine , tnx for report
Please upload a repro project here if possible, I could not compile your project properly
I also suggest that you remove the items inside the expander and place them one by one and test each time, the problem may be related to one of the items inside the expander.

**Comment by SunnieShine** [comment]
@ghost1372

I'm sorry that the project is too complex to be used. I just created a new project to re-produce the bug:

https://github.com/SunnieShine/SettingExpanderTest/tree/master

**Comment by SunnieShine** [comment]
@ghost1372 

Hey! It really works! Thank you! I'm sorry that the solution to this issue is very simple but I still don't solve it.
